addons:
  ssh_known_hosts: bjug.by
before_install:
  - wget https://github.com/spf13/hugo/releases/download/v0.16/hugo_0.16-1_i386.deb
  - sudo dpkg -i hugo_0.16-1_i386.deb
before_script:
  - openssl aes-256-cbc -K $encrypted_83630750896a_key -iv $encrypted_83630750896a_iv -in deploy@morty.enc -out ~/.ssh/deploy@morty -d
  - chmod 600 ~/.ssh/deploy@morty
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/deploy@morty
script:
  - bash ./deploy.sh
